// <auto-generated />
namespace Socializer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nullable_Birthdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nullable_Birthdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201606141758171_Nullable_Birthdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
